anguage: node_js
sudo: false
node_js:
  - "5.11"
cache:
  apt: true
  directories:
    - node_modules
addons:
  ssh_known_hosts: git.coding.net
script:
  - hexo clean && hexo generate
branches:
  only:
    - master
deploy:
  provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master