language: node_js
node_js:
- '4'
branches:
  only:
  - blog-source
env:
  global:
  - secure: N7phVL+y0dSAXkJSCHnRJKryyNIdUZs++VDkazzc8255kW2I4+UibLF4F9HqhlnjpwzIWvHTb8nXTyExOzscYfqKJ9+mF1bNKPLnvxPrgb49ELeyNC16+sEq0hOF94jkhkov+/N1NfgK+/m1T9duK/9HV7aSMlcMN4TNTNQDWy4gFi2x9ZjCcHJQTJK+r18e8Yt0YTJMwNaOX1wBHqZvuSBKZdf9tI2t5NPPQ4IbejQmzqzhtzeACBkpyE5LH3DcnLU3PYCIy2WaqGxiXqRLmzVkhohFrB6+Ac1UVpyDXRJiixWmZt+MyOOR+CFnUnjzp1+l9tUceR9UJhV8PCqhr4QrnZ9p2FJib+3Ekx3G6nnFmxxKJMqgLlboRtJyCEcqvIVUsuUN3UzkRF5yyRzkTyVLB8ApBsIAVv8jkIG/0lRfRd84DRXmt/9bOphxanJqtDPGfYtvxm+lR3/LQ6FSGTXsgs/kfpBz5ub82LUe9sMidYPeR5lk1Rk24KP5WmCLhAsvO20u7T9n5lakBJnWGklNrqDkBsJ6Zf42Nq6Pnx4p9h4D4SjPNVh0nd6MQ7Cz53iDJxEa2rZXD5mxHZFTJWEP33CNrQXiXW8DLSGXNmaPb0FGeq7dg7WkEIDpYjdD7acZ8F/zXSDTrRg/9Oym9mdTvA3AkyhK0VwHUTe026w=
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "liutf"
- git config --global user.email lautayfir@163.com
- sed -i'' "s~git@github.com:liutf/liutf.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/liutf/liutf.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy