language: node_js
node_js: stable

before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli

script:
  - sed -i'' "s~git@github.com:liutf/liutf.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/liutf/liutf.github.io.git~"
  _config.yml
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "liutf"
  - git config user.email "lautayfir@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/liutf/liutf.github.io.git