language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo-cli
- npm install hexo-generator-sitemap --save
- npm install hexo-generator-baidu-sitemap@0.1.1 --save
- npm install hexo-generator-feed --save

script:
  # - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "liutf"
  - git config user.email "lautayfir@163.com"
  - git add .
  - git commit -m "Travis CI"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/liutf/liutf.github.io.git
