language: node_js
node_js:
- '4'
branches:
  only:
  - blog-resource
env:
  global:
    secure: kYbE5cpL08ckCCM+wbLFN5jqaDr0mMvYFXrH9yN/82JVSIJ+RegCxOFhtCV6YVyE3jobUbY1PtY0xtMhvOGj3GILaLswA4pnnAlu+JZMMkZKnEr6dQ8URIzhbF5Y5mqMoQC6w6u6glvkhb5A37PPMOBtgzSuc9rjoPx9QgMYkoZsfl+UMv+DSad3w5AE50Cppvn4AY/U2ox7XKap5LgEI8LBESYKrujyz+msYhv6PlJDteavkddrxO5V9t/cmehjDH5+68rGRNxEI2aZltUGG+Bq0wEgap3DgT0KuskQPlifkYF5fRXKaLMLECylnUOzDSPXhPo+zX7fxuzd/FY6XmPaamW6wHdXtGzePr4KezMcY731iZCxdRk+Pye1gj/f8uNpP1id2vbpU7rX+/AaV0Blm13YqgK/UGEwi1pOpobg7JX63I7CnUvG1yo3Pb+thYuvirDRgqpihtTWqZ2bveK0QxG8IN5CJmajtQQe78Od57Pj58ciDvcSlgH0tpI6Dw/eObSuca7lSyBLO8LhE8U28R5HBVoohtqe/aaYiCgUk0csVAdRmVWdMUxKEEzvhlDfeOWWSzOftZ9rpo5LzVtI4Utx4ojCh9V+RZUdLEe1ZgN7CXh4/jgIBcf8CSBMOKpYN6icoPlUP3q9qAmQ3/sxFp/497uLWxW37qSePss=
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "liutf"
- git config --global user.email lautayfir@163.com
- sed -i'' "s~git@github.com:liutf/liutf.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/liutf/liutf.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
